#=======================
#General Settings
#=======================
#The name of the bot changing this has no effect
botName: BennerBot
#The username of the the twitch account you want the bot to use
#Leave this to "default" if you dont want a custom account
#I recommend creating a new account for this
twitchUsername: default
#Enter the OAuth password (for lack of a better word) for your twitch account
#This can be found here: http://www.twitchapps.com/tmi/
#Leave this to "default" if you dont want a custom account
#I recommend creating a new account for this
twitchOAuth: default
#the name of the twitch account to moderate
twitchChannel: biogenx2b
#The username of the the hitbox account you want the bot to use
#Leave this to "default" if you dont want a custom account
#I recommend creating a new account for this
hitboxUsername: default
#Enter the password for your hitbox account
#Dont worry this wont be scene by anybody but yourself
#Leave this to "default" if you dont want a custom account
#I recommend creating a new account for this
hitboxPassword: default
#the name of the hitbox account to moderate
hitboxChannel: jdbener
#This is used to do things such as change the stream title
#A very simple tutorial on how to get this value can be found here: http://discuss.dev.twitch.tv/t/how-to-set-title/390/2
#If left blank you wont be able to change your stream title with the bot
#kxq56ehskmckkwop1cxlybt9ggjgsm5
twitchAccessToken: kxq56ehskmckkwop1cxlybt9ggjgsm5
#weather or not bennerbot should announce his presence
incognitoMode: true
 
#=======================
#Output Settings
#=======================
#weather or not to enable sending output to a file or a GUI
enableOutput: true
#weather or not to be able to send messages to your users
enableUserOutput: true
#enable the button to resize your GUI display to its original size
enableResizeButon: true
#weather or not to shorten usernames, 
#long names can cause issues and users names longer than 32 characters will be trimed no matter what
#I recommend leaving this on
nameShortener: false
#Write the output to a clean file
#if output GUI is true this has to be true
WriteClean: true
#Write the output to a file that can be imported into obs
WriteDirty: true
#Weather or not to highlight messages that include your name in them
HighlighMessages: true
#Weather or not to display messages from "bennerbot"
enableBotMessages: true
#Weather or not user join messages will be displayed
enableJoinMessages: false
#Weather or not user leave messages will be displayed
enableLeaveMessages: false
#Weather or not messages that plugins create will be displayed
#I recommend leaving this off, some of these messages could get kinda "spammy"
enablePluginMessages: true
#the size of the GUI display in the format: x,y
defaultGUIDisplaySize: "400,600"
#set this to true to clear the database of colors when the system starts?
resetColorDatabase: false

#=======================
#Chat Moderation Settings
#=======================
#weather or not bennerbot should moderate your chat
#only set this to true if bennerbot has been modded on your channel
enableModeration: true
#How many warnings a user gets before being timed out
kickWarnings: 5
#How many warnings a user gets before being banned
banWarnings: 20
#Active Capitalazation Filter?
CapsFilter: true
#Activate URL Filtering
UrlFilter: true
#Activate message length Filtering
LengthFilter: true

#How what percentage of a message is required to be capitalized in order to activate the filter
#This is a decimal number where 1 = 100%
MaxCapsPercentage: .8
#Weather to filter out all the URLS in the file or all other URLS
#Setting this to 1 will filter out all other URLS
#Setting this to -1 will filter out all URLS in the file
URLWhiteORBlackList: -1
#The maximum length of a message
MaxMessageLength: 150

#=======================
#API Integration Settings
#=======================
#weather or not to display a notification when someone follows
enableFollowerNotifications: true
#This allows you to use the !title and !game commands
enableStatusandGameUpdateing: true
#Enable this if you want the emoticons loading to be displayed on the console (disable this if submiting a bug report i dont need an extra 20 thousand lines :p)
ShowEmoticonLoading: true
#Enable this if you want the most current emotion data (i recommend leaving this off, the ones included with your download are very upto date. This also creates alot of lag on your system)
enableAutoEmotes: false

#=======================
#Relay Settings
#=======================
#weather or not the Chat Relay is activated
activateRelay: true
#weather or not to display the source of a message in the relay
showSource: false
#weather or not to display the username in the message for messages sent with the GUI
showSendName: false

#======================
#Plugin System Settings
#======================
#weather or not to enable the Plugin System
enablePluginSystem: true

#=======================
#Output Settings
#=======================
USERMESSAGE: "<server> <mod><date> <span style='color:<color>'><user></span> <message>"