#=======================
#Connection Settings
#=======================
#the name of the twitch account to moderate
twitchChannel: raziadastra
#the name of the hitbox account to moderate
hitboxChannel: bennerbot

#=======================
#Relay Settings
#=======================
#weather or not the Chat Relay is activated
activateRelay: true
 
#=======================
#Output Settings
#=======================
#Weather or not to clean the output
cleanOutput: true
