#=======================
#General Settings
#=======================
#the name of the bot
botName: BennerBot
#the name of the twitch account to moderate
#this or the hitbox channel can be left as bennerbot if you dont have an account
twitchChannel: bennerbot
#the name of the hitbox account to moderate
hitboxChannel: bennerbot
#weather or not bennerbot should announce his presence
incognitoMode: false
 
#=======================
#Output Settings
#=======================
#weather or not to display the cleaning class 
enableOutput: true
#Weather or not to display the included GUI
OutputGUI: true
#Weather our not the output GUI has a text area for sending messages
#This GUI is not resizeable, turn this off if you want to resize your bot
enableUserMessages: false
#Write the output to a clean file
#if output GUI is true this has to be true
WriteClean: true
#Write the output to a file that can be imported into obs
WriteDirty: true
#Weather or not to display messages from "bennerbot"
enableBotMessages: true
#Weather or not user join messages will be displayed
enableJoinMessages: true
#Weather or not user leave messages will be displayed
enableLeaveMessages: true
#Weather or not messages that plugins create will be displayed
#I recommend leaving this off, some of these messages could get kinda "spammy"
enablePluginMessages: false

#=======================
#Chat Moderation Settings
#=======================
#weather or not bennerbot should moderate your chat
#only set this to true if bennerbot has been modded on your channel
enableModeration: true
#How many warnings a user gets before being timed out
kickWarnings: 5
#How many warnings a user gets before being banned
banWarnings: 20
#Active Capitalazation Filter?
CapsFilter: true
#Activate URL Filtering
UrlFilter: true
#Activate message length Filtering
LengthFilter: true

#How what percentage of a message is required to be capitalized in order to activate the filter
#This is a decimal number where 1 = 100%
MaxCapsPercentage: .8
#Weather to filter out all the URLS in the file or all other URLS
#Setting this to 1 will filter out all other URLS
#Setting this to -1 will filter out all URLS in the file
URLWhiteORBlackList: -1
#The maximum length of a message
MaxMessageLength: 150

#=======================
#Relay Settings
#=======================
#weather or not the Chat Relay is activated
activateRelay: true

#======================
#Plugin System Settings
#======================
#weather or not to enable the Plugin System
enablePluginSystem: true
